SELECT VERSION();

\set libfile '\''`pwd`'/aesgcm.so\'';

CREATE OR REPLACE LIBRARY AESGCM AS :libfile;
CREATE OR REPLACE FUNCTION AESGCM_Decrypt AS LANGUAGE 'C++' NAME 'AESGCMDecryptFactory' LIBRARY AESGCM;
CREATE OR REPLACE FUNCTION AESGCM_Decrypt AS LANGUAGE 'C++' NAME 'AESGCMDecryptWithVarcharADFactory' LIBRARY AESGCM;
CREATE OR REPLACE FUNCTION AESGCM_Decrypt AS LANGUAGE 'C++' NAME 'AESGCMDecryptWithVarbinaryADFactory' LIBRARY AESGCM;
CREATE OR REPLACE FUNCTION AESGCM_Encrypt AS LANGUAGE 'C++' NAME 'AESGCMEncryptFactory' LIBRARY AESGCM;
CREATE OR REPLACE FUNCTION AESGCM_Encrypt AS LANGUAGE 'C++' NAME 'AESGCMEncryptWithVarcharADFactory' LIBRARY AESGCM;
CREATE OR REPLACE FUNCTION AESGCM_Encrypt AS LANGUAGE 'C++' NAME 'AESGCMEncryptWithVarbinaryADFactory' LIBRARY AESGCM;
